/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIconArrowLeft: typeof import('@element-plus/icons-vue')['ArrowLeft']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    'IAntDesign-LeftOutlined': typeof import('~icons/ant-design/-left-outlined')['default']
    IAntDesignLeftOutlined: typeof import('~icons/ant-design/left-outlined')['default']
    IAntDesignRightOutlined: typeof import('~icons/ant-design/right-outlined')['default']
    'IBi-PlayFill': typeof import('~icons/bi/-play-fill')['default']
    IBiPlayFill: typeof import('~icons/bi/play-fill')['default']
    'IBx-Play': typeof import('~icons/bx/-play')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    IElIconArrowLeft: typeof import('~icons/el/icon-arrow-left')['default']
    IEpCirclePlus: typeof import('~icons/ep/circle-plus')['default']
    IEpHeadset: typeof import('~icons/ep/headset')['default']
    IEpIconArrowLeft: typeof import('~icons/ep/icon-arrow-left')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    'IFlatColorIcons:like': typeof import('~icons/flat-color-icons/like')['default']
    'IMi-Play': typeof import('~icons/mi/-play')['default']
    IMiPlay: typeof import('~icons/mi/play')['default']
    Index: typeof import('./components/Index.vue')['default']
    LyricView: typeof import('./components/lyric-view.vue')['default']
  }
}
