/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContaniner: typeof import('element-plus/es')['ElContaniner']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpCircleplus: typeof import('~icons/ep/circleplus')['default']
    IEpCirclePlus: typeof import('~icons/ep/circle-plus')['default']
    IEpMessage: typeof import('~icons/ep/message')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpSerach: typeof import('~icons/ep/serach')['default']
    IEpsimpleLineIconsFrame: typeof import('~icons/ep/simple-line-icons-frame')['default']
    IEpSimpleLineIconsFrame: typeof import('~icons/ep/simple-line-icons-frame')['default']
    'IFlatColorIcons-Like': typeof import('~icons/flat-color-icons/-like')['default']
    'IFlatColorIcons:like': typeof import('~icons/flat-color-icons/like')['default']
    Index: typeof import('./components/Index.vue')['default']
    ISimpleLineIconsFrame: typeof import('~icons/simple-line-icons/frame')['default']
    LyricView: typeof import('./components/lyric-view.vue')['default']
  }
}
